"""initial

Revision ID: 0b042fa2efd0
Revises: 
Create Date: 2026-07-29 11:48:51.957496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b042fa2efd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cache_artifact_type'), 'ai_cache', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_ai_cache_entity_id'), 'ai_cache', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ai_cache_generated_at'), 'ai_cache', ['generated_at'], unique=False)
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('ceo_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_base_fee', sa.Integer(), nullable=True),
    sa.Column('free_shipping_threshold', sa.Integer(), nullable=True),
    sa.Column('same_day_cutoff', sa.String(length=10), nullable=True),
    sa.Column('return_address', sa.Text(), nullable=True),
    sa.Column('return_fee', sa.Integer(), nullable=True),
    sa.Column('exchange_fee', sa.Integer(), nullable=True),
    sa.Column('cs_phone', sa.String(length=20), nullable=True),
    sa.Column('cs_hours', sa.String(length=100), nullable=True),
    sa.Column('logistics_company', sa.String(length=100), nullable=True),
    sa.Column('outbound_location', sa.String(length=255), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_settings')
    op.drop_index(op.f('ix_ai_cache_generated_at'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_entity_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_artifact_type'), table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
